### ISSUE TITLE
(CentOS 7) id: Cannot find the group of user with ID 44127942

### ISSUE THREAD

**Issue by d1ves** [kcaaj/bdvl#16]
target os:centos 7 x64
```
Target:

Compiling

                     ▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
                    ▓▓▓▓▓▓
               ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
               ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
               ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
            ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
           ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
            ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
                ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓


Eddy!
Name: tom
Creating installation directory.
Patched: /usr/lib64/ld-2.17.so
Copied: libgrubwszvmk.so.i686
Copied: libgrubwszvmk.so.x86_64
Installation finished.

Hacker:

sh ssh.sh tom 192.168.0.2 16666
connecting to tom@192.168.0.2 from port 16666.
tom@192.168.0.2s password:
id: Cannot find the group of user with ID 44127942
-bash-4.2$ cd /root
-bash: cd: /root: Insufficient permissions
```

**Comment by d1ves** [comment]
i need to run this command：
chmod u+s bash
to fix
but the administrator will find this~

**Comment by kcaaj** [comment]
`su root` straight after getting the shell.
Or make the magic GID value a little smaller.
Let me know if neither work.

**Comment by d1ves** [comment]
1，
``
-bash-4.2$ su root
Segfault
```
2，
```
/usr/bin/id:Cannot find the group of user with ID 31495071
-bash-4.2$ cd /root
-bash: cd: /root: Insufficient permissions
```

**Comment by kcaaj** [comment]
Manually set the default magic GID in `setup.py` to `65534`. Perhaps the system isn't okay with trying to use an unsigned int.
Kernel?

**Comment by d1ves** [comment]
GID with 0 or 65534 is the same error

**Comment by kcaaj** [comment]
I've kind of found the culprit... Along with a quick fix for the time being.
As soon as you are logged into the backdoor, do the following:
```
su -
cd
. .bashrc
```

**Comment by d1ves** [comment]
It works!
good job
about the SELinux,my target is close
Centos 7 x64 Without SELinux
good job~👍👍👍👍👍👍👍👍👍👍

**Comment by d1ves** [comment]
when you update the code ,the errors is same
:(

**Comment by kcaaj** [comment]
The commit I have just pushed makes dealing with this a little less annoying.
All you need do is `su -` & the kit will handle the rest. Keeping this open though.

**Comment by kcaaj** [comment]
> 1，
> 
> ```
> -bash-4.2$ su root
> Segfault
> ```
> 
> 2，
> 
> ```
> /usr/bin/id:Cannot find the group of user with ID 31495071
> -bash-4.2$ cd /root
> -bash: cd: /root: Insufficient permissions
> ```

In the most recent commits that segfault is gone. That `Cannot find the group of user with ID` message will also no longer pop up, but that does not *actually* do much practically. `su -` is still required on login. Thanks again.

**Comment by kcaaj** [comment]
Update!:
This issue has been resolved. Please read [this commit](https://github.com/kcaaj/bdvl/commit/c1231613f5f9ca0a134d9875a18851e1da0f867f) for more information.
